config/routes.rb
Rails.application.routes.draw do
  resources :weekends
  resources :semesters
  resources :courses
  resources :grades
  resources :periods
  #---------------------------

#################################### RUTAS DE ASISTENCIAS
  resources :assistances
  get 'teacher/dashboard/editar/asistencias/:id' => 'assistances#teacher_assistances_edit_form', as: 'teacher_editar_asistencia'
  #----------------------------------

##################################### RUTA ROOT
  get 'welcome/index'
  root 'welcome#index'
  #-----------------------
###################################### RUTA RAILS_ADMIN
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #---------------------------

############################################ RUTA DE LOS PROFESORES
  devise_for :teachers, path_prefix:'profesor'
  resources :teachers
  get 'teacher/curso/:id' => 'teachers#curso', as: 'teacher_curso'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'
  get 'teacher/dashboard/asistencia/:id' => 'teachers#asistencia_curso', as: 'teacher_asistencia'
  #---------------------------------

############################################ RUTAS DE LOS ESTUDIANTES
  devise_for :students, path_prefix:'estudiante'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/courses_curso/:id' => 'students#courses_curso', as: 'student_courses_curso'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'
  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'
  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'
  #----------------------------

############################################# RUTA DEL USUARIO ADMIN
  devise_for :users, path_prefix:'usuario'
  resources :users
  #---------------------------

############################################# RUTAS DE LAS NOTAS
  resources :scores
  get 'score/teacher_edit_form/:id' => 'scores#teacher_edit_form', as: 'teacher_edit_form'
  #--------------------
##################################################
  devise_for :parents, path_prefix:'familia'
  resources :parents

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :grades
  has_many :scores
  has_many :assistances
  has_many :semesters
  has_and_belongs_to_many :parents
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :change_grade_student, :enroll_student]

  before_action :authenticate_user!, except: [:dashboard, :courses_curso, :grade, :profile]
  before_action :authenticate_student!, only: [:dashboard, :courses_curso, :grade, :profile]

  layout "Admin"
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #----------------------------//////////
  def change_grade_student
  end

  def enroll_student
    grade = Grade.find(params[:id])

    grade.courses.each do |v|
      v.scores.create(student_id: @student.id)
    end

    if @student.grades << grade
      redirect_to students_path, notice: "El estudiante ha sido asignado a este grado"
    else
      logger.alert 'CAMBIO NO SATISFACTIRO'
      render :change_grade_student
    end


  end
# area administrativa de estudiandes-------------------
  def dashboard
    #debe mostrar datos personales del estudiante
    #las materias que esta cursando y el grado actual
    @courses = current_student.grades.actual.first.courses unless current_student.grades.actual.blank?


    #mostrar lo que ya ha cursado
    @grades_old = current_student.grades.where(current: false) unless current_student.grades.where(current: false).blank?

  end
  def courses_curso
    #mostras los datos del curso solicitado, incluyendo las notas
    @course = Course.find(params[:id])
    @scores = @course.scores.find_by student_id: current_student
  end
  def grade
    @grade = Grade.find(params[:id])
    @ss = 1
    @grade.courses.each do |c|
      @ss = @ss + c.scores.where(student_id: current_student).first.score_final if c.scores.any?
    end
    @result = @ss/@grade.courses.count
  end
  def profile
    @student = current_student
  end

#------------------------/-/--/-/-/-/-/-/-/-//-
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit([:name,:last_name, :email, :password])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/change_grade_student.html.erb
<h1>Cambiar Grado</h1>
<h2><%=link_to "Atras", :back, class: "btn btn-primary"%></h2>
<hr>
<h3>Estudiante: <strong> <%= "#{@student.name } #{@student.last_name}"%> </strong></h3>

<p><strong>Grado Actual:</strong> <%= @student.grades.where(current: true).first.name unless @student.grades.where(current: true).blank? %></p>

<p><strong>Periodo Actual:</strong> <%= @student.grades.where(current: true).first.period.name unless @student.grades.where(current: true).blank? %></p>


<%= form_tag(action: :enroll_student ) do %>

	<%= hidden_field_tag :id, @student.id %>
	<%= label_tag 'Nuevo grado'%>
	<%= select_tag :grade_id, options_for_select(set_grades.collect{ |modelo| ["#{modelo.name} #{modelo.period.name}", modelo.id]}) %>
	<%= submit_tag 'Cambiar', class: 'btn btn-primary'%>



<%end%>

app/views/students/courses_curso.html.erb
<%= link_to "atras" , student_dashboard_path, class: "btn btn-primary m-1 float-xs-right float-sm-right float-md-right float-lg-right"%>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    <h1 >Detalles del Curso</h1>
    <table class="table">
      <tbody>
        <tr>
          <th class="h2" scope="row">Profesor: </th>
          <td class="h2"><%=link_to "#{@course.teacher.name} #{@course.teacher.last_name}", "mailto:#{@course.teacher.email} "%></td>
        </tr>
        <tr>
          <th class="h2" scope="row">Materia:</th>
          <td class="h2"><%= @course.name%></td>
        </tr>
        <tr>
          <th class="h2" scope="row">Grado: </th>
          <td class="h2"><%= "#{@course.grade.name} #{@course.grade.period.name}"%></td>
        </tr>
        <tr>
          <th class="h2">Estado:</th>
          <td class="h2">
            <% if @course.grade.current?%>
                <span style="padding: 0.3em;" class="text-white bg-success">Cursando</span>
            <%else%>
                <span class="text-white bg-warning">Finalizado</span>
            <%end%>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-md-4 col-md-4">

  </div>
</div>
<%if @scores.blank?%>
     <h1>Tus calificaciones aun no han sido publicadas</h1>
<%else%>
    <div class="row">
        <h1 class="ml-2">Calificaciones</h1>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Primer Semestre</th>
                  <th>Notas</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Primera Nota</th>
                  <td>
                    <%if @scores.score_one == 0-%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_one%></span>
                    <%elsif @scores.score_one <= 69 %>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_one%></span>
                    <%elsif @scores.score_one <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_one%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_one%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Segunda Nota</th>
                  <td>
                    <%if @scores.score_two == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_two%></span>
                    <%elsif @scores.score_two <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_two%></span>
                    <%elsif @scores.score_two <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_two%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_two%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Tercera Nota</th>
                  <td>
                    <%if @scores.score_three == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_three%></span>
                    <%elsif @scores.score_three <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_three%></span>
                    <%elsif @scores.score_three <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_three%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_three%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Cuarta Nota</th>
                  <td>
                    <%if @scores.score_four == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_four%></span>
                    <%elsif @scores.score_four <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_four%></span>
                    <%elsif @scores.score_four <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_four%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_four%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Examen</th>
                  <td>
                    <%if @scores.score_test == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_test%></span>
                    <%elsif @scores.score_test <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_test%></span>
                    <%elsif @scores.score_test <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_test%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_test%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Nota Final</th>
                  <td>
                    <%if @scores.score_final == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_final%></span>
                    <%elsif @scores.score_final <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_final%></span>
                    <%elsif @scores.score_final <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_final%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_final%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Completivo</th>
                  <td colspan="2">En espera</td>
                </tr>
                <tr>
                  <th scope="row">Extraordinario</th>
                  <td colspan="2">En espera</td>
                </tr>
              </tbody>
            </table>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Segundo Semestre</th>
                  <th>Notas</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Primera Nota</th>
                  <td>
                    <%if @scores.score_one == 0-%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_one%></span>
                    <%elsif @scores.score_one <= 69 %>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_one%></span>
                    <%elsif @scores.score_one <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_one%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_one%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Segunda Nota</th>
                  <td>
                    <%if @scores.score_two == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_two%></span>
                    <%elsif @scores.score_two <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_two%></span>
                    <%elsif @scores.score_two <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_two%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_two%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Tercera Nota</th>
                  <td>
                    <%if @scores.score_three == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_three%></span>
                    <%elsif @scores.score_three <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_three%></span>
                    <%elsif @scores.score_three <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_three%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_three%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Cuarta Nota</th>
                  <td>
                    <%if @scores.score_four == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_four%></span>
                    <%elsif @scores.score_four <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_four%></span>
                    <%elsif @scores.score_four <= 79%>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_four%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_four%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Examen</th>
                  <td>
                    <%if @scores.score_test == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_test%></span>
                    <%elsif @scores.score_test <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_test%></span>
                    <%elsif @scores.score_test <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_test%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_test%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Nota Final</th>
                  <td>
                    <%if @scores.score_final == 0%>
                      <span style="padding: 0.5em;" class="text-white bg-default"><%=@scores.score_final%></span>
                    <%elsif @scores.score_final <= 69%>
                      <span style="padding: 0.5em;" class="text-white bg-danger"><%=@scores.score_final%></span>
                    <%elsif @scores.score_final <= 79 %>
                      <span style="padding: 0.5em;" class="text-white bg-warning"><%=@scores.score_final%></span>
                    <%else%>
                      <span style="padding: 0.5em;" class="text-white bg-success"><%=@scores.score_final%></span>
                    <%end%>
                  </td>
                </tr>
                <tr>
                  <th scope="row">Completivo</th>
                  <td colspan="2">En espera</td>
                </tr>
                <tr>
                  <th scope="row">Extraordinario</th>
                  <td colspan="2">En espera</td>
                </tr>
              </tbody>
            </table>
        </div>
      </div>
<%end%>

app/views/students/dashboard.html.erb
<div class="dashboard">
	<div class="jumbotron ">

		<h1 class="text-center">
			Hola <%= "#{current_student.name} #{current_student.last_name}"%>
		</h1>

		<p><strong>Grado Actual: </strong><%=current_student.grades.actual.first.name unless current_student.grades.actual.blank?%></p>
		<p><strong>Periodo: </strong><%=current_student.grades.actual.first.period.name unless current_student.grades.actual.blank?%></p>
		<%= link_to 'Ver Mi Perfil', student_profile_path, class: "btn btn-primary ml-3"%>


	</div>
</div>
<%if @courses.blank?%>
<h1>Ups lo siento, no tengo notas de ninguna materia tuya</h1>
<%else%>
	<div>
		<% @courses.each_with_index do |a, b|%>


			<div class="row-fluid">
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">

								<%= link_to "Detalles del curso" , student_courses_curso_path(a), class: "btn btn-primary my-1"%>

						<table class="table table-bordered">
						  <thead>
						    <tr class="table-active">
						      <th><%= "Materia: "%></th>
						      <td><%= "#{a.name}" %> </td>
						    </tr>
						  </thead>
						  <tbody>
						    <tr class="table-active">
						      <th scope="row"><%= "Estudiante: "%></th>
						      <td><%= "#{current_student.name.upcase} #{current_student.last_name.upcase}" %></td>
						    </tr>
						    <tr class="table-active">
						      <th scope="row"><%= "Maestro: "%></th>
						      <td><%= "#{a.teacher.name.upcase} #{a.teacher.last_name.upcase}"%></td>
						    </tr>
						    <tr class="table-active">
						      <th scope="row"><%= "Periodo" %></th>
						      <td><%= a.grade.period.name%></td>
						    </tr>
								<tr class="table-active">
						      <th scope="row"><%= "Estado" %></th>
						      <td class="bg-info text-white">
										<% if a.grade.current? %>
										<span class="w-100 ">Cursando</span>
									</td>
									<%else%>
									<td class="bg-success text-white">
										<span class="label label-warning">Finalizado</span>
										<%end%>
									</td>
						    </tr>
						  </tbody>
						</table>
					</div>
			</div>

			<%end%>


		</div>
<%end%>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/grade.html.erb
<h1><%=link_to "Atras", student_dashboard_path %></h1>

<h2>Grado: <%="#{@grade.name} #{@grade.period.name}" %></h2>
<h2>
    <% if @grade.current?%>
        <apan class="label label-success">Cursando</apan>
    <%else%>
        <apan class="label label-waring">Finalizado</apan>
    <%end%>

</h2>
<h1>
    <%if @result >= 65 %>
        <p>
          <a class="btn btn-md btn-success">Promovido</a>
          con un promedio de <%= @result %>
        </p>
    <%else%>
    <a class="btn btn-md btn-success">Reprovado</a>
    con un promedio de <%= @result %>

    <%end%>
</h1>

<h1>
<% @grade.courses.each do |v, k| %>
      <th scope="row"><%k+1%></th>
      <td> <%=v.name%></td>
      <td> <%="#{v.teacher.name} #{v.teache.last_name}"%></td>
      <p>
        <%= v.scores.where(student_id: current_student).first.score_final if scores.any?%>
      </p>
  <%end%>

</h1>
<h1>

app/views/students/index.html.erb
 <%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:email) %></th>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:genere) %></th>
      <th><%= model_class.human_attribute_name(:birth) %></th>
      <th><%= model_class.human_attribute_name(:mother) %></th>
      <th><%= model_class.human_attribute_name(:father) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>

        <td><%= student.email %></td>

        <td><%= student.name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.genere %></td>
        <td><%= student.birth %></td>
        <td><%= student.mother %></td>
        <td><%= student.father %></td>


        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-default btn-xs' %>

          <%=link_to 'Cambiar Grado', change_grade_student_path(student), class: 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/profile.html.erb
<div class="jumbotron">
  <h1><%="#{@student.name} #{@student.last_name}"%></h1>
  <h2>Mi prefil</h2>
  <h5><%=link_to "Atras", student_dashboard_path, class: "btn btn-primary mt-2"%></h5>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Datos Del Estudiantes</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">Teléfono del Estudiante</th>
            <td><%= @student.phone%></td>
          </tr>
          <tr>
            <th scope="row">Email</th>
            <td><%= @student.email%></td>
          </tr>
          <tr>
            <th scope="row">Padre</th>
            <td><%= @student.father%></td>
          </tr>
          <tr>
            <th scope="row">Teléfono del Padre</th>
            <td>809-000-0001</td>
          </tr>
          <tr>
            <th scope="row">Madre</th>
            <td><%= @student.mother%></td>
          </tr>
          <tr>
            <th scope="row">Teléfono de la Madre</th>
            <td>809-000-0003</td>
          </tr>
          <tr>
            <th scope="row">Fecha de Nacimiento</th>
            <td colspan="2"><%= @student.birth%></td>
          </tr>
          <tr>
            <th scope="row">Grago Actual</th>
            <td colspan="2">
              <%@student.grades.each do |d|%>
              <span style="padding: 0.5em;" class="bg-success text-white tags">Dañado<%"#{d.name} #{d.period.name}"%></span>
            <%end%>
          </tr>
        </tbody>
      </table>
  </div>



</div>