config/routes.rb
Rails.application.routes.draw do
  resources :weekends
  resources :semesters
  resources :courses
  resources :grades
  resources :periods
  #---------------------------

#################################### RUTAS DE ASISTENCIAS
  resources :assistances
  get 'teacher/dashboard/editar/asistencias/:id' => 'assistances#teacher_assistances_edit_form', as: 'teacher_editar_asistencia'
  #----------------------------------

##################################### RUTA ROOT
  get 'welcome/index'
  root 'welcome#index'
  #-----------------------
###################################### RUTA RAILS_ADMIN
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #---------------------------

############################################ RUTA DE LOS PROFESORES
  devise_for :teachers, path_prefix:'profesor'
  resources :teachers
  get 'teacher/curso/:id' => 'teachers#curso', as: 'teacher_curso'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'
  get 'teacher/dashboard/asistencia/:id' => 'teachers#asistencia_curso', as: 'teacher_asistencia'
  #---------------------------------

############################################ RUTAS DE LOS ESTUDIANTES
  devise_for :students, path_prefix:'estudiante'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/courses_curso/:id' => 'students#courses_curso', as: 'student_courses_curso'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'
  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'
  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'
  #----------------------------

############################################# RUTA DEL USUARIO ADMIN
  devise_for :users, path_prefix:'usuario'
  resources :users
  #---------------------------

############################################# RUTAS DE LAS NOTAS
  resources :scores
  get 'score/teacher_edit_form/:id' => 'scores#teacher_edit_form', as: 'teacher_edit_form'
  #--------------------
##################################################
  devise_for :parents, path_prefix:'familia'
  resources :parents

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assistance.rb
class Assistance < ApplicationRecord

  belongs_to :student
  belongs_to :course
  belongs_to :semester
  belongs_to :weekend
  belongs_to :teacher
end

app/models/course.rb
 class Course < ApplicationRecord
 	has_many :scores
 	belongs_to :teacher
 	belongs_to :grade
  
  ################
  #parte de dylan
  has_many :assistances



  ###################
 	validates :name, presence: true

  scope :actules, -> {where grade_id: Grade.where(current: true)}
  scope :viejo, -> {where grade_id: Grade.where(current: false)}

end

app/models/grade.rb
class Grade < ApplicationRecord
	belongs_to :period
	has_and_belongs_to_many :students
	has_many :courses
	validates :name, presence: true

	scope :actual, -> {where current: true}
end

app/models/parent.rb
class Parent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :students
  has_many :parents
end

app/models/period.rb
class Period < ApplicationRecord
	has_many :grades 
	validates :name, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :course
	belongs_to :student

	before_save :update_final_score
	protected 
	def update_final_score
		final = (self.score_one + self.score_two + self.score_three + self.score_four + self.score_test) / 5 
		self.score_final = final
	end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :assistances
  belongs_to :course
  belongs_to :user
  belongs_to :period
  has_many :students
  validates :name, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :grades
  has_many :scores
  has_many :assistances
  has_many :semesters
  has_and_belongs_to_many :parents
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :semesters
end

app/models/weekend.rb
class Weekend < ApplicationRecord
    has_many :assistances
    validates :week, presence: true
end

app/controllers/assistances_controller.rb
class AssistancesController < ApplicationController
  before_action :set_assistance, only: [:show, :edit, :update, :destroy, :teacher_assistances_edit_form]


  before_action :authenticate_user!, except: [:teacher_assistances_edit_form, :update]
  before_action :authenticate_teacher!, only: [:teacher_assistances_edit_form, :update]

  layout "Admin"

  # GET /assistances
  # GET /assistances.json
  ########################################
  def teacher_assistances_edit_form
  end
  ########################################
  def index
    @assistances = Assistance.all
  end

  # GET /assistances/1
  # GET /assistances/1.json
  def show
  end

  # GET /assistances/new
  def new
    @assistance = Assistance.new
  end

  # GET /assistances/1/edit
  def edit
  end

  # POST /assistances
  # POST /assistances.json
  def create
    @assistance = Assistance.new(assistance_params)

    respond_to do |format|
      if @assistance.save
        format.html { redirect_to @assistance, notice: 'Assistance was successfully created.' }
        format.json { render :show, status: :created, location: @assistance }
      else
        format.html { render :new }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistances/1
  # PATCH/PUT /assistances/1.json
  def update
    respond_to do |format|
      if @assistance.update(assistance_params)
        format.html { redirect_to @assistance, notice: 'Assistance was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistance }
      else
        format.html { render :edit }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistances/1
  # DELETE /assistances/1.json
  def destroy
    @assistance.destroy
    respond_to do |format|
      format.html { redirect_to assistances_url, notice: 'Assistance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistance
      @assistance = Assistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assistance_params
      params.require(:assistance).permit(:day1, :day2, :day3, :day4, :day5, :day6, :day7, :today, :student_id, :weekend_id, :semester_id, :course_id)
    end
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weekends_helper.rb
module WeekendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assistances/_form.html.erb
<%= form_for(assistance) do |f| %>
  <% if assistance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assistance.errors.count, "error") %> prohibited this assistance from being saved:</h2>

      <ul>
      <% assistance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day1 %>
    <%= f.text_field :day1 %>
  </div>
  <div class="field">
    <%= f.label :day2 %>
    <%= f.text_field :day2 %>
  </div>
  <div class="field">
    <%= f.label :day3 %>
    <%= f.text_field :day3 %>
  </div>
  <div class="field">
    <%= f.label :day4 %>
    <%= f.text_field :day4 %>
  </div>
  <div class="field">
    <%= f.label :day5 %>
    <%= f.text_field :day5 %>
  </div>



  <div class="field">
    <%= f.label :Estudiante %>
    <%= f.select :student_id, set_students.collect{|v| ["#{v.name} #{v.last_name}", v.id]}, {}, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :Curso %>
    <%= f.select :course_id, set_courses.collect{|a| [a.name, a.id]}, {}, :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :Semana %>
    <%= f.select :weekend_id, set_weekend.collect{|c| [c.week,c.id]}, {}, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :Semestre %>
    <%= f.select :semester_id, set_semester.collect{|b| [b.name, b.id]}, {}, :class => 'form-control'%>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assistances/edit.html.erb
<h1>Editing Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Show', @assistance %> |
<%= link_to 'Back', assistances_path %>

app/views/assistances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assistances</h1>

<table>
  <thead>
    <tr>
      <th>Day1</th>
      <th>Day2</th>
      <th>Day3</th>
      <th>Day4</th>
      <th>Day5</th>


      <th>Course</th>
      <th>Profesor</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistances.each do |assistance| %>
      <tr>
        <td><%= assistance.day1 %></td>
        <td><%= assistance.day2 %></td>
        <td><%= assistance.day3 %></td>
        <td><%= assistance.day4 %></td>
        <td><%= assistance.day5 %></td>

        <td><%= assistance.course.name %></td>
        <td><%= "#{assistance.course.teacher.name} #{assistance.course.teacher.last_name}" %></td>

        <td><%= "#{assistance.student.name} #{assistance.student.last_name}" %></td>
        <td><%= link_to 'Show', assistance %></td>
        <td><%= link_to 'Edit', edit_assistance_path(assistance) %></td>
        <td><%= link_to 'Destroy', assistance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assistance', new_assistance_path %>

app/views/assistances/new.html.erb
<h1>New Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Back', assistances_path %>

app/views/assistances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day1:</strong>
  <%= @assistance.day1 %>
</p>
<p>
  <strong>Day2:</strong>
  <%= @assistance.day2 %>
</p>
<p>
  <strong>Day3:</strong>
  <%= @assistance.day3 %>
</p>
<p>
  <strong>Day4:</strong>
  <%= @assistance.day4 %>
</p>
<p>
  <strong>Day5:</strong>
  <%= @assistance.day5 %>
</p>


<p>
  <strong>Course:</strong>
  <%= @assistance.course.name %>
</p>
<p>
  <strong>Profesor:</strong>
  <%= "#{@assistance.course.teacher.name } #{@assistance.course.teacher.last_name }" %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= %>
</p>

<p>
  <strong>Student:</strong>
  <%="#{@assistance.student.name} #{@assistance.student.last_name}" %>
</p>

<%= link_to 'Edit', edit_assistance_path(@assistance) %> |
<%= link_to 'Back', assistances_path %>

app/views/assistances/teacher_assistances_edit_form.html.erb
<h1>Aqui va el formulario para editar las asistencias</h>
<h1><%= link_to "atras", :back%></h1>
<%= form_for @assistance do |f| %>


  <div class="field">
    <%= f.label :day1 %>
    <%= f.text_field :day1 %>
  </div>
  <div class="field">
    <%= f.label :day2 %>
    <%= f.text_field :day2 %>
  </div>
  <div class="field">
    <%= f.label :day3 %>
    <%= f.text_field :day3 %>
  </div>
  <div class="field">
    <%= f.label :day4 %>
    <%= f.text_field :day4 %>
  </div>
  <div class="field">
    <%= f.label :day5 %>
    <%= f.text_field :day5 %>
  </div>



  <div class="field">
    <%= f.label :Estudiante %>
    <%= f.select :student_id, set_students.collect{|v| ["#{v.name} #{v.last_name}", v.id]}, {}, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :Curso %>
    <%= f.select :course_id, set_courses.collect{|a| [a.name, a.id]}, {}, :class => 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :Semana %>
    <%= f.select :weekend_id, set_weekend.collect{|c| [c.week,c.id]}, {}, :class => 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :Semestre %>
    <%= f.select :semester_id, set_semester.collect{|b| [b.name, b.id]}, {}, :class => 'form-control'%>
  </div>


  <div class="actions">
    <%= f.submit nil %>
  </div>
<% end %>