config/routes.rb
Rails.application.routes.draw do
  resources :weekends
  resources :semesters
  resources :courses
  resources :grades
  resources :periods
  #---------------------------

#################################### RUTAS DE ASISTENCIAS
  resources :assistances
  get 'teacher/dashboard/editar/asistencias/:id' => 'assistances#teacher_assistances_edit_form', as: 'teacher_editar_asistencia'
  #----------------------------------

##################################### RUTA ROOT
  get 'welcome/index'
  root 'welcome#index'
  #-----------------------
###################################### RUTA RAILS_ADMIN
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #---------------------------

############################################ RUTA DE LOS PROFESORES
  devise_for :teachers, path_prefix:'profesor'
  resources :teachers
  get 'teacher/curso/:id' => 'teachers#curso', as: 'teacher_curso'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'
  get 'teacher/dashboard/asistencia/:id' => 'teachers#asistencia_curso', as: 'teacher_asistencia'
  #---------------------------------

############################################ RUTAS DE LOS ESTUDIANTES
  devise_for :students, path_prefix:'estudiante'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/courses_curso/:id' => 'students#courses_curso', as: 'student_courses_curso'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'
  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'
  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'
  #----------------------------

############################################# RUTA DEL USUARIO ADMIN
  devise_for :users, path_prefix:'usuario'
  resources :users
  #---------------------------

############################################# RUTAS DE LAS NOTAS
  resources :scores
  get 'score/teacher_edit_form/:id' => 'scores#teacher_edit_form', as: 'teacher_edit_form'
  #--------------------
##################################################
  devise_for :parents, path_prefix:'familia'
  resources :parents

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assistance.rb
class Assistance < ApplicationRecord

  belongs_to :student
  belongs_to :course
  belongs_to :semester
  belongs_to :weekend
  belongs_to :teacher
end

app/models/course.rb
 class Course < ApplicationRecord
 	has_many :scores
 	belongs_to :teacher
 	belongs_to :grade
  
  ################
  #parte de dylan
  has_many :assistances



  ###################
 	validates :name, presence: true

  scope :actules, -> {where grade_id: Grade.where(current: true)}
  scope :viejo, -> {where grade_id: Grade.where(current: false)}

end

app/models/grade.rb
class Grade < ApplicationRecord
	belongs_to :period
	has_and_belongs_to_many :students
	has_many :courses
	validates :name, presence: true

	scope :actual, -> {where current: true}
end

app/models/parent.rb
class Parent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :students
  has_many :parents
end

app/models/period.rb
class Period < ApplicationRecord
	has_many :grades 
	validates :name, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :course
	belongs_to :student

	before_save :update_final_score
	protected 
	def update_final_score
		final = (self.score_one + self.score_two + self.score_three + self.score_four + self.score_test) / 5 
		self.score_final = final
	end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :assistances
  belongs_to :course
  belongs_to :user
  belongs_to :period
  has_many :students
  validates :name, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :grades
  has_many :scores
  has_many :assistances
  has_many :semesters
  has_and_belongs_to_many :parents
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :semesters
end

app/models/weekend.rb
class Weekend < ApplicationRecord
    has_many :assistances
    validates :week, presence: true
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weekends_helper.rb
module WeekendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bare - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->


    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Bienvenido</h1>
                <p class="lead">School online</p>
                <ul class="list-unstyled">
                	<%if current_user%>
                		<li><%=link_to "System", grades_path, class: "btn btn-success"%></li>

                	<%elsif current_student%>
                		<li><%=link_to "System", student_dashboard_path, class: "btn btn-success"%></li>

                	<%elsif current_teacher%>
                		<li><%=link_to "System", teacher_dashboard_path, class: "btn btn-success"%></li>
                	<%else%>
                		<li><%=link_to "Login User", new_user_session_path, class: "btn btn-primary"%></li>
                    	<br>
                    	<li><%=link_to "Login Student", new_student_session_path, class: "btn btn-primary"%></li>
                    	<br>
                    	<li><%=link_to "Login Teacher", new_teacher_session_path, class: "btn btn-primary"%></li>
                    <%end%>


                	<br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <li>@Dy_Innova</li>
                    <li>Innova_code klk :)</li>


                </ul>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>