config/routes.rb
Rails.application.routes.draw do
  resources :weekends
  resources :semesters
  resources :courses
  resources :grades
  resources :periods
  #---------------------------

#################################### RUTAS DE ASISTENCIAS
  resources :assistances
  get 'teacher/dashboard/editar/asistencias/:id' => 'assistances#teacher_assistances_edit_form', as: 'teacher_editar_asistencia'
  #----------------------------------

##################################### RUTA ROOT
  get 'welcome/index'
  root 'welcome#index'
  #-----------------------
###################################### RUTA RAILS_ADMIN
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #---------------------------

############################################ RUTA DE LOS PROFESORES
  devise_for :teachers, path_prefix:'profesor'
  resources :teachers
  get 'teacher/curso/:id' => 'teachers#curso', as: 'teacher_curso'
  get 'teacher/dashboard' => 'teachers#dashboard', as: 'teacher_dashboard'
  get 'teacher/dashboard/asistencia/:id' => 'teachers#asistencia_curso', as: 'teacher_asistencia'
  #---------------------------------

############################################ RUTAS DE LOS ESTUDIANTES
  devise_for :students, path_prefix:'estudiante'
  resources :students
  get 'student/dashboard' => 'students#dashboard', as: 'student_dashboard'
  get 'student/courses_curso/:id' => 'students#courses_curso', as: 'student_courses_curso'
  get 'student/grade/:id' => 'students#grade', as: 'student_grade'
  get 'student/profile' => 'students#profile', as: 'student_profile'
  get 'student/change_grade/:id' => 'students#change_grade_student', as: 'change_grade_student'
  post 'student/enroll_student' => 'students#enroll_student', as: 'enroll_student'
  #----------------------------

############################################# RUTA DEL USUARIO ADMIN
  devise_for :users, path_prefix:'usuario'
  resources :users
  #---------------------------

############################################# RUTAS DE LAS NOTAS
  resources :scores
  get 'score/teacher_edit_form/:id' => 'scores#teacher_edit_form', as: 'teacher_edit_form'
  #--------------------
##################################################
  devise_for :parents, path_prefix:'familia'
  resources :parents

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assistance.rb
class Assistance < ApplicationRecord

  belongs_to :student
  belongs_to :course
  belongs_to :semester
  belongs_to :weekend
  belongs_to :teacher
end

app/models/course.rb
 class Course < ApplicationRecord
 	has_many :scores
 	belongs_to :teacher
 	belongs_to :grade
  
  ################
  #parte de dylan
  has_many :assistances



  ###################
 	validates :name, presence: true

  scope :actules, -> {where grade_id: Grade.where(current: true)}
  scope :viejo, -> {where grade_id: Grade.where(current: false)}

end

app/models/grade.rb
class Grade < ApplicationRecord
	belongs_to :period
	has_and_belongs_to_many :students
	has_many :courses
	validates :name, presence: true

	scope :actual, -> {where current: true}
end

app/models/parent.rb
class Parent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :students
  has_many :parents
end

app/models/period.rb
class Period < ApplicationRecord
	has_many :grades 
	validates :name, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :course
	belongs_to :student

	before_save :update_final_score
	protected 
	def update_final_score
		final = (self.score_one + self.score_two + self.score_three + self.score_four + self.score_test) / 5 
		self.score_final = final
	end
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :assistances
  belongs_to :course
  belongs_to :user
  belongs_to :period
  has_many :students
  validates :name, presence: true

end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :grades
  has_many :scores
  has_many :assistances
  has_many :semesters
  has_and_belongs_to_many :parents
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :semesters
end

app/models/weekend.rb
class Weekend < ApplicationRecord
    has_many :assistances
    validates :week, presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:curso, :dashboard, :edit, :update, :show, :asistencia_curso]
  before_action :authenticate_teacher!, only: [:curso, :dashboard, :edit, :update, :asistencia_curso]

  layout "Admin"
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
#/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-///-/-/-/-/
  def curso
     @course = Course.find(params[:id])
  end

  def dashboard
    #listar las materias que esta impartiendo
    @materia_cursando = current_teacher.courses.actules
    @materias_viejas = current_teacher.courses.viejo
    #lisar las materia
  end
  def asistencia_curso
     @curso = Course.find(params[:id])
  end
#-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/--/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
    @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit([:name, :last_name, :phone, :about, :email, :password])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weekends_helper.rb
module WeekendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher, :html => { :class => "form-horizontal teacher" } do |f| %>

  <% if @teacher.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_password) %>
  </div>
  
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label :about, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :about, :class => 'form-control' %>
    </div>
    <%=f.error_span(:about) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                teachers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/teachers/asistencia_curso.html.erb
<h1><%= link_to "atras", teacher_curso_path %></h1>

<%if @curso.blank? %>

  <h1>aun no hay asistencias asignadas a este curso</h1>
<%else%>
    <h1><%@curso.assistances.each_with_index do |s|%></h1>
    <h1><%=s.day1%></h1>
    <h1><%=s.day2%></h1>
    <h1><%=s.day3%></h1>
    <h1><%=s.day4%></h1>
    <h1><%=s.day5%></h1>
    <h1><%=%></h1>
    <h1>Profesor: <%="#{@curso.teacher.name} #{@curso.teacher.last_name}"%></h1>
    <h1>Estudiante: <%="#{s.student.name} #{s.student.last_name}"%></h1>
    <h1>Materia: <%="#{@curso.name}"%></h1>
    <h1><%=link_to "editar asistencia", teacher_editar_asistencia_path(s)%></h1>
    <hr>
    <%end%>
<%end%>

app/views/teachers/curso.html.erb
<h2><%= link_to "Dashboard", teacher_dashboard_path, class: "btn btn-primary"%></h2>
<th>
    <%=link_to "Asistencia", teacher_asistencia_path(@course), class: "btn btn-info btn-sm"%>
</th>
  <%if @course.scores.blank?%>
    <h1 class="display-4 bg-warning text-white text-center p-1">Sin Notas Publicadas</h1>
  <%else%>
<hr>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th class="text-center">Materia: <%=@course.name%></th>
        <th class="text-center">Profesor: <%=@course.teacher.name%></th>
        <th class="text-center">Estato:
        <%if @course.grade.current?%>
            <span class="label label-success">Cursando</span>
        <%else%>
          <span class="label label-warning">Finalizado</span>
        <%end%></th>
      
      </tr>
    </thead>
  </table>
</div>
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

  <% @course.scores.each_with_index do |a, b|%>
    <table class="table table-bordered">
      <thead class="thead-default">
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Primera Nota</th>
          <th>Segunda Nota</th>
          <th>Tercera Nota</th>
          <th>Cuarta Nota</th>
          <th>Examen</th>
          <th>Nota Final</th>
          <th><i class="fa fa-wrench" aria-hidden="true"></i></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><%=b+1%></th>
          <td><%="#{a.student.name} #{a.student.last_name}" %></td>
          <td>
            <%if a.score_one == 0-%>
              <span class="label label-default"><%=a.score_one%></span>
            <%elsif a.score_one <= 69 %>
              <span class="label label-danger"><%=a.score_one%></span>
            <%elsif a.score_one <= 79 %>
              <span class="label label-warning"><%=a.score_one%></span>
            <%else%>
              <span class="label label-success"><%=a.score_one%></span>
            <%end%>
          </td>
          <td>
            <%if a.score_two == 0%>
              <span class="label label-default"><%=a.score_two%></span>
            <%elsif a.score_two <= 69%>
              <span class="label label-danger"><%=a.score_two%></span>
            <%elsif a.score_two <= 79%>
              <span class="label label-warning"><%=a.score_two%></span>
            <%else%>
              <span class="label label-success"><%=a.score_two%></span>
            <%end%>
          </td>
          <td>
            <%if a.score_three == 0%>
              <span class="label label-default"><%=a.score_three%></span>
            <%elsif a.score_three <= 69%>
              <span class="label label-danger"><%=a.score_three%></span>
            <%elsif a.score_three <= 79%>
              <span class="label label-warning"><%=a.score_three%></span>
            <%else%>
              <span class="label label-success"><%=a.score_three%></span>
            <%end%>
          </td>
          <td>
            <%if a.score_four == 0%>
              <span class="label label-default"><%=a.score_four%></span>
            <%elsif a.score_four <= 69%>
              <span class="label label-danger"><%=a.score_four%></span>
            <%elsif a.score_four <= 79%>
              <span class="label label-warning"><%=a.score_four%></span>
            <%else%>
              <span class="label label-success"><%=a.score_four%></span>
            <%end%>
          </td>
          <td>
            <%if a.score_test == 0%>
              <span class="label label-default"><%=a.score_test%></span>
            <%elsif a.score_test <= 69%>
              <span class="label label-danger"><%=a.score_test%></span>
            <%elsif a.score_test <= 79 %>
              <span class="label label-warning"><%=a.score_test%></span>
            <%else%>
              <span class="label label-success"><%=a.score_test%></span>
            <%end%>
          </td>
          <td>
            <%if a.score_final == 0%>
              <span class="label label-default"><%=a.score_final%></span>
            <%elsif a.score_final <= 69%>
              <span class="label label-danger"><%=a.score_final%></span>
            <%elsif a.score_final <= 79 %>
              <span class="label label-warning"><%=a.score_final%></span>
            <%else%>
              <span class="label label-success"><%=a.score_final%></span>
            <%end%>
          </td>
          <td>
            <%= link_to "Editar Nota", teacher_edit_form_path(a), class: "btn btn-info btn-sm"%>
          </td>
          <%end%>
          <% end%>
        </tr>
      </tbody>
    </table>

</div>

app/views/teachers/dashboard.html.erb
<div class="jumbotron jumbotron-fluid">
<h1>Hola Maestro <%="#{current_teacher.name.upcase} #{current_teacher.last_name.upcase}"%></h1>
<br>
<h2>Materias Actuales:</h2>
</div>
<div>

    <% @materia_cursando.each_with_index do |a, b|%>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
      <table class="table table-bordered">
          <tbody>
            <tr>
              <th scope="row">Materia <%=b+1%></th>
              <td><%=a.name %></td>
            </tr>
            <tr>
              <th scope="row">Grado:</th>
              <td><%=a.grade.name %></td>
            </tr>
            <tr>
              <th scope="row">Periodo:</th>
              <td><%=a.grade.period.name %></td>
            </tr>
            <tr>
              <th scope="row">Estado:</th>
              <td class="bg-info text-white">
                <% if a.grade.current? %>
                <span class="w-100 ">Cursando</span>
              </td>
              <%else%>
              <td class="bg-success text-white">
                <span class="label label-warning">Finalizado</span>
                <%end%>
              </td>

            </tr>
          </tbody>
      </table>
      <h4>
        <%= link_to "Ver Detalles", teacher_curso_path(a), class: "nav-link btn btn-outline-primary btn-lg"%>

      </h4>
      <br>
      <br>
    </div>
    <%end%>
</div>

app/views/teachers/edit.html.erb
<div class="page-header">
  <h1>Mi perfil</h1>
  <h1><%= link_to "Dashboard", teacher_dashboard_path, class: "btn btn-success"%></h1>
</div>

<%= form_for @teacher, :html => { :class => "form-horizontal teacher" } do |f| %>


  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_password) %>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_name) %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label :about, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :about, :class => 'form-control' %>
    </div>
    <%=f.error_span(:about) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil , :class => 'btn btn-primary' %>

    </div>
  </div>

<% end %>

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>

      <th><%= model_class.human_attribute_name(:email) %></th>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:about) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>

        <td><%= teacher.email %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.phone %></td>
        <td><%= teacher.about %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teacher_path(teacher),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teacher_path,
            :class => 'btn btn-primary' %>

app/views/teachers/new.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for @teacher, :html => { :class => "form-horizontal teacher" } do |f| %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :phone %><br />
      <%= f.number_field :phone %>
    </div>

    <div class="field">
      <%= f.label :about %><br />
      <%= f.text_area :about %>
    </div>


    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>

<%end%>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1>Mi perfil</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @teacher.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teacher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @teacher.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @teacher.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:about) %>:</strong></dt>
  <dd><%= @teacher.about %></dd>
</dl>
<%if current_teacher%>
  <%=link_to "Dashboard", teacher_dashboard_path, class: "btn btn-info"%>
  <%=link_to "Atras", :back, class: "btn btn-default" %>
<%else%>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%end%>